#do this first (in main directory)
sudo docker build --tag fastapi_graphql_sqlalchemy_container dependencies/.

#then do this in main directory 
sudo docker run -it --rm --mount type=bind,source="$(pwd)"/,target=/code -w /code fastapi_graphql_sqlalchemy_container bash

#command to remove container (can also do in docker dekstop)
docker rm fastapi_graphql_sqlalchemy_container

#exit container 
exit

#everything else should be the same as normal linux