version: '3.8'
services:
  db: 
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3336:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'
volumes:
  mysql_data: